name: Build with Maven

# on:
#   pull_request:
#     branches:
#       - main # запускать только для PR в main
on:
  push:
    branches:
      - "**"

jobs:
  build-job:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9-eclipse-temurin-21

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Java version
        run: |
          echo "Using Java version:"
          java -version

      - name: Build, test and package with Maven
        run: mvn -B clean test package

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifacts
          path: target/*.jar
